version: '3'

# Define services
services:
    # App backend service
    app-server:
        # Configuration for building the docker image for the backend service
        build:
            context: . # Use an image built from the specified dockerfile in the directory specific.
            dockerfile: Dockerfile
        container_name: "mutantexam"        
        ports:
            - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
        restart: always
        depends_on:
            - db # This service depends on mysql. Start that first.
        environment: # Pass environment variables to the service
            SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mutantexamdb
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: admin 
        networks: # Networks to join (Services on the same network can communicate with each other using their name)
            - backend
    db:
        image: "postgres:11"
        container_name: "postgres11"
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=mutantexamdb
            - PGDATA=/var/lib/postgresql/data/pgdata
        networks: # Networks to join (Services on the same network can communicate with each other using their name)
            backend:
                aliases:
                    - postgreshost

volumes:
    db-data:

networks:
    backend:
        driver: bridge